sudo: required
dist: trusty
addons:
  firefox: 'latest'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "node"
  - "6"
script:
  - xvfb-run npm test
  - xvfb-run npm run test:integration
before_script:
  - npm install -g bower
  - npm install -g polymer-cli
  - npm install
  - bower install